### ISSUE TITLE
UFC not recognizing DCS

### ISSUE THREAD

**Issue by amvvafonso** [AlphaMikeSimulation/HornetUFCDCS#6]
Hello, I've been trying to use this app but it can't seem to find DCS, plus if I hit the shut down button, im unable to restart the app with the start button

**Comment by ChrisLargo** [comment]
Did you use the last DCS update? I have the same problem since I have update DCS with the last patch (2.9.3.51704).

**Comment by amvvafonso** [comment]
Yes I do, no a single app recognises it. Not even SRS :/

**Comment by AlphaMikeSimulation** [comment]
Issue should be fixed now with release 1.3 of the app. please download the update and let me know if you still have issues
